name: CI

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.os }}, ${{ matrix.ocaml.version || matrix.ocaml }})
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        ocaml: [{version: '4.02',
                 repo: 'archive: git+https://github.com/ocaml/opam-repository-archive.git'},
                '4.03',
                '4.04',
                '4.05',
                '4.06',
                '4.07',
                '4.08',
                '4.09',
                '4.10',
                '4.11',
                '4.12',
                '4.13',
                '4.14',
                '5.0',
                '5.1',
                '5.2',
                '5.3']
        include:
          - os: windows-latest
            ocaml: '4.13'
          - os: windows-latest
            ocaml: '5.3'
          - os: macos-13
            ocaml: {version: '4.02',
                    pin: 'camlp-streams git+https://github.com/dra27/camlp-streams.git#old',
                    repo: 'archive: git+https://github.com/ocaml/opam-repository-archive.git'}
          - os: macos-latest
            ocaml: '5.3'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.build.ocaml }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml.version || matrix.ocaml }}
          opam-repositories: |-
            default: git+https://github.com/ocaml/opam-repository.git
            ${{ matrix.ocaml.repo }}

      - run: opam pin add bitmasks.dev . --no-action
      - name: ${{ matrix.ocaml.pin && format('opam pin add {0}', matrix.ocaml.pin) || 'opam pin hhotfixes' }}
        if: matrix.ocaml.pin
        run: opam pin add --no-action ${{ matrix.ocaml.pin }}
      - run: opam install . --deps-only --with-doc --with-test
      - run: opam exec -- dune build @install @runtest
      - run: opam exec -- make doc
