name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.02.3
          - 4.03.0
          - 4.04.2
          - 4.05.0
          - 4.06.1
          - 4.07.1
          - 4.08.1
          - 4.09.1
          - 4.10.2
          - 4.11.2
          - 4.12.0
        include:
          - os: windows-latest
            ocaml-version: 4.02.3
          - os: windows-latest
            ocaml-version: 4.12.0
          - os: macos-latest
            ocaml-version: 4.02.3
          - os: macos-latest
            ocaml-version: 4.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set-up OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add bitmasks.dev . --no-action
      - run: opam install . --deps-only --with-doc --with-test
      - run: opam exec -- dune build @install @runtest
      - run: opam exec -- make doc
